### ISSUE TITLE
After npm start, my bot saying this

### ISSUE THREAD

**Issue by destiny6520** [HashHackers/aria-telegram-mirror-bot#2]
@ParveenBhadooOfficial 
@HashHackers

>
> ![IMG_20200517_225121](https://user-images.githubusercontent.com/53997345/82155382-27e22280-9892-11ea-82f9-85325ea528f9.jpg)
> 
> ![Screenshot_2020-05-17-22-50-48-243_org telegram messenger](https://user-images.githubusercontent.com/53997345/82155386-2b75a980-9892-11ea-9927-8a4efa46a739.jpg)
>

**Comment by ParveenBhadooOfficial** [comment]
Use
https://github.com/out386/aria-telegram-mirror-bot

**Comment by destiny6520** [comment]
@ParveenBhadooOfficial 

Used out386's repo also
https://github.com/out386/aria-telegram-mirror-bot


Getting same error 

Pls help @ParveenBhadooOfficial

**Comment by ParveenBhadooOfficial** [comment]
In .constants.js
On Line 4 do this

ARIA_DOWNLOAD_LOCATION: '/app/downloads)',

**Comment by destiny6520** [comment]
@ParveenBhadooOfficial 

**getting same error**
saying read only file system.


![Screenshot_2020-05-18-13-19-08-969_com termux](https://user-images.githubusercontent.com/53997345/82188242-37518200-990b-11ea-852a-634b8660dfc7.jpg)
![Screenshot_2020-05-18-13-18-55-362_org telegram messenger](https://user-images.githubusercontent.com/53997345/82188249-3ae50900-990b-11ea-83e7-d8afee85ae8d.jpg)

**Comment by ParveenBhadooOfficial** [comment]
Telegram @TheFirstSpeedster
